version: 0.2
env:
  shell: /bin/sh
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      # Install node dependencies
      - npm install
  build:
    commands:
      # Build project
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build